version: '2'
services:
  dbase:
    container_name: "dbase"
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=statistics
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 8711:8711

  webapp:
    container_name: "webapp"
    build: .
    environment:
      - MYSQL_URI=dbase:8711
      - MYSQL_DATABASE=statistics
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 8710:8710
      - 8712:8712
    links:
      - "dbase:webapp"
