version: '2'
services:
  db:
    container_name: "db"
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=statistics
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ".dump.sql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  webapp:
    container_name: "webapp"
    build: .
    environment:
      - MYSQL_URI=db:3306
      - MYSQL_DATABASE=statistics
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "8080:8080"
      - "9990:9990"
    links:
      - "db:webapp"
