version: '3'
services:
  db:
    image: mysql
    ports:
    - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=statistics
    networks:
      - autoparts
  wildfly:
    build: ../
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - ../target/ROOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war

    networks:
      - autoparts
networks:
  autoparts:
    driver: bridge